// This file is auto-generated by KSP. Do not edit manually.
import ImdbSDK
import SwiftUI

public struct MoviesScreenRepresentable: UIViewControllerRepresentable {
    public func makeUIViewController(context _: Context) -> UIViewController {
        MoviesScreenUIViewController().make()
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        // unused
    }
}
