// This file is auto-generated by KSP. Do not edit manually.
import ImdbSDK
import SwiftUI

public struct SearchScreenRepresentable: UIViewControllerRepresentable {
    public func makeUIViewController(context _: Context) -> UIViewController {
        SearchScreenUIViewController().make()
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        // unused
    }
}
