name: ComposeMultiplatformImdbDemo
options:
  bundleIdPrefix: com.dallaslabs
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

packages:
  ImdbSDKPackage:
    path: SDKPackage

targets:
  ComposeMultiplatformImdbDemo:
    type: application
    platform: iOS
    sources:
      - ComposeMultiplatformImdbDemo
    info:
      path: ComposeMultiplatformImdbDemo/Info.plist
      properties:
        CFBundleDisplayName: CMP IMDB
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
        CADisableMinimumFrameDurationOnPhone: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dallaslabs.ComposeMultiplatformImdbDemo
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: ImdbSDKPackage
        product: ImdbSDK
